### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by toas-koas** [dic1911/android_AutoDND#1]
Initially worked. But also not always. Sometimes it worked for an app, sometimes not. 
When I went to the launcher, the DND mode was often not disabled. 
Currently it doesn't work at all. 
I reinstalled the app and gave all permissions.

I use a Pixel 2XL with CalyxOS Android 11. 
The app has the version 2.0.

**Comment by im030** [comment]
I couldn't reproduce this issue on my device, mind post what apps/games that you use AutoDND with?

**Comment by toas-koas** [comment]
It's working now. I don't know why
