### ISSUE TITLE
Light theme is next to unusable

### ISSUE THREAD

**Issue by StSav012** [dic1911/android_AutoDND#12]
Here's how it looks for me:

![Screenshot_20240406-171119.png](https://github.com/dic1911/android_AutoDND/assets/10685968/a355f3ae-306b-4b35-8cc5-bda347102a56)

When the dark theme's on, the app looks good:

![Screenshot_20240406-171323.png](https://github.com/dic1911/android_AutoDND/assets/10685968/7666f0e2-d9c2-4b54-842d-e1bbdd446289)

**Comment by im030** [comment]
@StSav012 please test the latest release

**Comment by StSav012** [comment]
Thank you for the quick fix. The theme is always dark now, which suits me.
