### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by plutonium-239** [dic1911/android_AutoDND#13]
Hi, I've been using this app for a few months, and it was working well initially. However, since last month, I've had no progress getting it to work. 

I only have 2 apps in my allow list (Camo and Youtube Music).

On every phone restart, the app crashes right after unlocking the phone (maybe because shizuku doesn't start automatically, have to start wireless debugging manually). But then I enable shizuku and open the autodnd app manually but it doesn't seem to have any effect. Other apps relying on shizuku do work, such as Ambient Music Mod and ColorBlendr.

**Comment by im030** [comment]
Sorry for the late reply, force stop, run the app and finish setup like you just got it installed will fix your issue.

**Comment by plutonium-239** [comment]
Thanks that fixes it :)
Seems like I need to do it every time I restart though :(
