### ISSUE TITLE
Selected App Not Added

### ISSUE THREAD

**Issue by kd4e** [dic1911/android_AutoDND#2]
When I click on an app to add it - the popup says it was added - but it doesn't show up on the list.
Pixel 4a with GrapheneOS (google-purged android).

**Comment by im030** [comment]
This issue doesn't exist on my side, please record a video and send logcat so I can look into it.

**Comment by ghost** [comment]
> When I click on an app to add it - the popup says it was added - but it doesn't show up on the list. Pixel 4a with GrapheneOS (google-purged android).

FYI actually it's added but list doesn't updated or refreshed can you make it happen? @dic1911

**Comment by im030** [comment]
> FYI actually it's added but list doesn't updated or refreshed can you make it happen? @dic1911

Guess I should rollback some dataset update code, will make a test build tomorrow, thx for the info!

**Comment by ghost** [comment]
> > FYI actually it's added but list doesn't updated or refreshed can you make it happen? @dic1911
> 
> Guess I should rollback some dataset update code, will make a test build tomorrow, thx for the info!

yw do you have any telegram group? to discuss it?
also where you will post test build?

**Comment by im030** [comment]
> > > FYI actually it's added but list doesn't updated or refreshed can you make it happen? @dic1911
> > 
> > 
> > Guess I should rollback some dataset update code, will make a test build tomorrow, thx for the info!
> 
> yw do you have any telegram group? to discuss it? also where you will post test build?

It will be an attached file in here, and no, I don't have a group for my apps (yet)

**Comment by ghost** [comment]
> FYI actually it's added but list doesn't updated or refreshed can you make it happen? @dic1911
>  Guess I should rollback some dataset update code, will make a test build tomorrow, thx for the info!
> > yw do you have any telegram group? to discuss it? also where you will post test build?
> 
> It will be an attached file in here, and no, I don't have a group for my apps (yet)

bruh 🗿🗿🗿🗿

**Comment by im030** [comment]
> bruh moyaimoyaimoyaimoyai

Don't spam please, I was too tired yesterday, anyway here's the test build(2.0-A)

[AutoDND-2.0-A.zip](https://github.com/dic1911/android_AutoDND/files/8009467/AutoDND-2.0-A.zip)

**Comment by ghost** [comment]
> Don't spam please, I was too tired yesterday, anyway here's the test build(2.0-A)
sorry sir that isn't my intention i just do reactions

> [AutoDND-2.0-A.zip](https://github.com/dic1911/android_AutoDND/files/8009467/AutoDND-2.0-A.zip)

well done sir after test list now lively updated  :-)

remaining task is add placeholder

**Comment by im030** [comment]
> remaining task is add placeholder

No, I don't take "orders", keep yourself in proper manner or get ignored next time.

**Comment by ghost** [comment]
> > remaining task is add placeholder
> 
> No, I don't take "orders", keep yourself in proper manner or get ignored next time.

sorry I don't have any intention like that sir what i want to do is just remind if you don't mind 🙏

**Comment by im030** [comment]
> > > remaining task is add placeholder
> > 
> > 
> > No, I don't take "orders", keep yourself in proper manner or get ignored next time.
> 
> sorry I don't have any intention like that sir what i want to do is just remind if you don't mind pray

Of course I would mind, I already rejected your request in another issue, so stop asking.

**Comment by ghost** [comment]
> > > > remaining task is add placeholder
> > > 
> > > 
> > > No, I don't take "orders", keep yourself in proper manner or get ignored next time.
> > 
> > 
> > sorry I don't have any intention like that sir what i want to do is just remind if you don't mind pray
> 
> Of course I would mind, I already rejected your request in another issue, so stop asking.

okay i respect all developer decision regarding to this issues:
https://github.com/dic1911/android_AutoDND/issues/3

btw why my issues locked as spam? i didn't spam tho :-/ 🙏😔
