### ISSUE TITLE
Few improvement

### ISSUE THREAD

**Issue by ghost** [dic1911/android_AutoDND#3]
1. add placeholder notification:
- FYI app can get killed by system automatically without a reason and funny things is sometime it happen even after change battery setting 🗿🗿🗿🗿
2. make list better:
- allow user to refresh list without need to restart
- display list live

**Comment by im030** [comment]
1. Which ROM/device are you using? I never have this issue with both my Pixel XL and 4a 5G on LineageOS 18.0~19.0

2. Agreed, I'll need some time to figure out how to do it clean though.

**Comment by ghost** [comment]
> 1. Which ROM/device are you using? I never have this issue with both my Pixel XL and 4a 5G on LineageOS 18.0~19.0

Realme 5i 
RMX2030
Android 10 Realme UI 1.0


> 2. Agreed, I'll need some time to figure out how to do it clean though.

bruh 🗿🗿🗿🗿

**Comment by im030** [comment]
> Realme

Well, if it's due to Chinese modded ROM, I feel sorry for you but I'm not gonna clean their a** for anyone, your best bet is to unlock bootloader and flash a "proper" ROM.

**Comment by ghost** [comment]
> > Realme
> 
> Well, if it's due to Chinese modded ROM, I feel sorry for you but I'm not gonna clean their a** for anyone

that's mean you won't add placeholder notification?

>your best bet is to unlock bootloader and flash a "proper" ROM.

please understand that not all people is expert on thosr things
I'm newbie and i definitely can't do that since there is no recovery tools for android :-/

**Comment by im030** [comment]
> that's mean you won't add placeholder notification?

Yup, I don't support Chinese ROM as they're non-standard anyway, by fixing issue appears only on Chinese ROM indirectly means I support their dumb modifications and decisions, so no, I won't fix it.

**Comment by im030** [comment]
Refresh button added in 9c58abd
