### ISSUE TITLE
Missing Packages?

### ISSUE THREAD

**Issue by weismantelf** [dic1911/android_AutoDND#5]
Hello,
I am missing in your AutoDND the following package:

- moe.dic1911.autodnd.databinding.FragmentMainBinding 
- moe.dic1911.autodnd.databinding.FragmentMainBinding.inflate

Can you tell me, where I can find it?

with best  regards

Frank

**Comment by im030** [comment]
You're probably doing it wrong, simply import this repo in Android Studio and build should just work
