### ISSUE TITLE
Is it possible to choose system apps?

### ISSUE THREAD

**Issue by RAPXT** [dic1911/android_AutoDND#6]
Maybe i didn't found it, but is there a way to choose system apps? If not, it would be nice if you could add that.

The intention would be, to start the clock app (to set an alarm) and have the phone automatically go to DND mode.

[It does however work quite fine with user installed clocks, but sadly I can't use them because they don't fire alarms reliably.]

**Comment by im030** [comment]
Currently it's not implemented, but I think I'll find some time to work on this later.

**Comment by im030** [comment]
Implemented in 2.1, closing as done.
