### ISSUE TITLE
Not work on my android 13

### ISSUE THREAD

**Issue by francesco-cadei** [dic1911/android_AutoDND#9]
Error message "Please allow this app to access/modify notification policy".
But I have granted `All AutoDND notifications`.

**Comment by francesco-cadei** [comment]
I have also tried with `Auto DND toggle` but still have "This service is malfunctioning".

**Comment by im030** [comment]
Please provide logcat otherwise I can't help much, one other thing is to make sure you're not on stock ROM if your phone is from one of the China brands.

**Comment by im030** [comment]
Closing due to no details provided and inactivity.
